apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sumail829/contactmanager-backend
        ports:
        - containerPort: 8000
        env: 
        - name: DATABASE_URL
          value: "postgresql+asyncpg://samir:postgres@postgres:5432/contact_db"
